/* Generated by re2c 0.13.5 on Sat Jul 19 10:54:42 2014 */
#line 1 "c_token.tem.c"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "c_token.h"


MyToken* NewToken(char *file, long startLine, long startCol,
	long endLine, long endCol, char* tokenStart, char* tokenEnd, int type)
{
	MyToken *token;
	int tokenLen = tokenEnd - tokenStart;
	char *tokenName = NULL;

	if((token = (MyToken*)malloc(sizeof(MyToken))) == NULL)
		return NULL;
	if( tokenLen == 0 || (tokenName = (char*)malloc(tokenLen + 1)) == NULL)
	{
		free(token);
		return NULL;
	}

	memset(token, 0, sizeof(MyToken));
	strncpy(tokenName, tokenStart, tokenLen);
	tokenName[tokenLen] = 0;
	
	token->file = file;
	token->startLine = startLine;
	token->startCol = startCol;
	token->endLine = endLine;
	token->endCol = endCol;
	token->name = tokenName;
	token->tokenType = type;

//	printf("Add token %s, %d:%d - %d:%d\n", token->name, startLine, startCol, endLine, endCol);

	return token;
}

/*
PushToken(TokenNode* tokenStack, MyToken* token)
{
}

MyToken* PopToken(TokenNode* tokenStack)
{
}*/

TokenNode* AddToken(TokenNode* tokenList,  MyToken* token)
{
	if(token == NULL || tokenList == NULL)
		return NULL;
	TokenNode *tokenNode = NULL;
	if((tokenNode = (TokenNode*)malloc(sizeof(TokenNode))) == NULL)
		return NULL;
	memset(tokenNode, 0, sizeof(TokenNode));
	tokenNode->mime = token;
	tokenNode->next = tokenList;
	//scope->tokenList.prev point to last tokenNode
	tokenNode->prev = tokenList->prev;
	tokenList->prev->next = tokenNode;
	tokenList->prev = tokenNode;
	return tokenNode;
}

TokenNode* DelTokenNode(TokenNode* delTokenNode)
{
	TokenNode *nextNode;
	printf("del token %s\n",delTokenNode->mime->name);
	delTokenNode->prev->next = delTokenNode->next;
	delTokenNode->next->prev = delTokenNode->prev;
	nextNode = delTokenNode->prev;
	free(delTokenNode);
	return nextNode;
}


TokenNode* InsertToken(TokenNode* insertPoint,  MyToken* token)
{
	if(token == NULL || insertPoint == NULL)
		return NULL;
	TokenNode *newTokenNode = NULL;
	printf("intert token %s\n",token->name);
	if((newTokenNode = (TokenNode*)malloc(sizeof(TokenNode))) == NULL)
		return NULL;
	memset(newTokenNode, 0, sizeof(TokenNode));
	newTokenNode->mime = token;

	newTokenNode->next = insertPoint->next;
	newTokenNode->prev = insertPoint;
	insertPoint->next->prev = newTokenNode;
	insertPoint->next = newTokenNode;

	return newTokenNode;
}





MyToken* NextToken(TokenNode** nextNode)
{
retry:
	*nextNode = (*nextNode)->next;
	if((*nextNode)->mime->tokenType == EOFILE)
		return NULL;
	if((*nextNode)->mime->tokenType == SPACE)
		goto retry;
	return (*nextNode)->mime;
}


#define	YYCTYPE		char
#define	YYCURSOR	yyCursor
#define	YYLIMIT		yyLimit
#define	YYMARKER	yyMarker
#define	YYFILL(n)	
#define ADD_TOKEN(X)  	{\
	endLine = currLine;	\
	endCol = (int)(yyCursor - lineStart) -1; \
	AddToken(tokenList, \
	NewToken(fileName, startLine, startCol, endLine, endCol, yyToken, yyCursor,(X))); \
	}



int OpenTokenFile(char *fileName, TokenNode *tokenList){
	char *buffer, *lineStart;
	char *yyMarker, *yyLimit, *yyCursor, *yyToken;
	int currLine = 0, startLine = 0, startCol = 0, endLine = 0, endCol = 0;
	int fileSize, readCount;
	FILE* tokenFd;
	int currPos;

	tokenFd = fopen(fileName, "rb");
	if(tokenFd == NULL)
		return -1;
	fseek(tokenFd, 0, SEEK_END);
	fileSize = ftell(tokenFd);
	fseek(tokenFd, 0, SEEK_SET);
	buffer = (char*)malloc(fileSize+1);
	if(buffer == NULL) return -1;
	lineStart = yyCursor = yyToken = yyMarker = buffer;
	yyLimit = buffer + fileSize;

	readCount= 0;
	while(readCount != fileSize)
	{
		readCount += fread(buffer+readCount, 1, 4096, tokenFd);
	}
	buffer[readCount] = 0;

	fclose(tokenFd);
	
	for(;;)
	{
		yyToken = yyCursor;
		startLine = currLine;
		startCol = (int)(yyToken - lineStart);
			
		#line 173 "c_token.tem.c"


		
#line 170 "c_token.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 14) YYFILL(14);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy81;
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy23;
	case '\n':	goto yy79;
	case '\r':	goto yy78;
	case '!':	goto yy54;
	case '"':	goto yy33;
	case '#':	goto yy21;
	case '%':	goto yy44;
	case '&':	goto yy46;
	case '\'':	goto yy29;
	case '(':	goto yy66;
	case ')':	goto yy68;
	case '*':	goto yy42;
	case '+':	goto yy38;
	case ',':	goto yy62;
	case '-':	goto yy40;
	case '.':	goto yy31;
	case '/':	goto yy2;
	case '0':	goto yy26;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy28;
	case ':':	goto yy64;
	case ';':	goto yy56;
	case '<':	goto yy36;
	case '=':	goto yy52;
	case '>':	goto yy34;
	case '?':	goto yy76;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'x':
	case 'y':
	case 'z':	goto yy25;
	case '[':	goto yy70;
	case ']':	goto yy72;
	case '^':	goto yy48;
	case '_':	goto yy20;
	case 'a':	goto yy4;
	case 'b':	goto yy6;
	case 'c':	goto yy7;
	case 'd':	goto yy8;
	case 'e':	goto yy9;
	case 'f':	goto yy10;
	case 'g':	goto yy11;
	case 'i':	goto yy12;
	case 'l':	goto yy13;
	case 'r':	goto yy14;
	case 's':	goto yy15;
	case 't':	goto yy16;
	case 'u':	goto yy17;
	case 'v':	goto yy18;
	case 'w':	goto yy19;
	case '{':	goto yy58;
	case '|':	goto yy50;
	case '}':	goto yy60;
	case '~':	goto yy74;
	default:	goto yy83;
	}
yy2:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy484;
	case '/':	goto yy482;
	case '=':	goto yy480;
	default:	goto yy3;
	}
yy3:
#line 289 "c_token.tem.c"
	{ ADD_TOKEN('/'); continue;}
#line 288 "c_token.c"
yy4:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'u':	goto yy476;
	default:	goto yy185;
	}
yy5:
#line 238 "c_token.tem.c"
	{ ADD_TOKEN(ID); continue;}
#line 298 "c_token.c"
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy471;
	default:	goto yy185;
	}
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy452;
	case 'h':	goto yy453;
	case 'o':	goto yy454;
	default:	goto yy185;
	}
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy434;
	case 'o':	goto yy435;
	default:	goto yy185;
	}
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy416;
	case 'n':	goto yy417;
	case 'v':	goto yy418;
	case 'x':	goto yy419;
	default:	goto yy185;
	}
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy408;
	case 'o':	goto yy409;
	default:	goto yy185;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy404;
	default:	goto yy185;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy394;
	case 'n':	goto yy396;
	default:	goto yy185;
	}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy390;
	default:	goto yy185;
	}
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy377;
	default:	goto yy185;
	}
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy344;
	case 'i':	goto yy345;
	case 't':	goto yy346;
	case 'w':	goto yy347;
	default:	goto yy185;
	}
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy337;
	default:	goto yy185;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy325;
	default:	goto yy185;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy314;
	default:	goto yy185;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy309;
	default:	goto yy185;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy248;
	default:	goto yy185;
	}
yy21:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '#':	goto yy189;
	default:	goto yy193;
	}
yy22:
#line 227 "c_token.tem.c"
	{ ADD_TOKEN(PP_SHARP); continue;}
#line 410 "c_token.c"
yy23:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy187;
yy24:
#line 297 "c_token.tem.c"
	{ ADD_TOKEN(SPACE); continue;}
#line 418 "c_token.c"
yy25:
	yych = *++YYCURSOR;
	goto yy185;
yy26:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy160;
	case 'X':
	case 'x':	goto yy177;
	default:	goto yy176;
	}
yy27:
#line 242 "c_token.tem.c"
	{ ADD_TOKEN(ICON); continue;}
#line 437 "c_token.c"
yy28:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy158;
yy29:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy30;
	default:	goto yy148;
	}
yy30:
#line 307 "c_token.tem.c"
	{
			printf("unexpected character: %c\n", yyToken);
			continue;
		}
#line 455 "c_token.c"
yy31:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy136;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy137;
	default:	goto yy32;
	}
yy32:
#line 282 "c_token.tem.c"
	{ ADD_TOKEN('.'); continue;}
#line 476 "c_token.c"
yy33:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy30;
	default:	goto yy126;
	}
yy34:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy119;
	case '>':	goto yy121;
	default:	goto yy35;
	}
yy35:
#line 292 "c_token.tem.c"
	{ ADD_TOKEN('>'); continue;}
#line 494 "c_token.c"
yy36:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '<':	goto yy115;
	case '=':	goto yy113;
	default:	goto yy37;
	}
yy37:
#line 291 "c_token.tem.c"
	{ ADD_TOKEN('<'); continue;}
#line 505 "c_token.c"
yy38:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '+':	goto yy109;
	case '=':	goto yy111;
	default:	goto yy39;
	}
yy39:
#line 287 "c_token.tem.c"
	{ ADD_TOKEN('+'); continue;}
#line 516 "c_token.c"
yy40:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy105;
	case '=':	goto yy107;
	case '>':	goto yy103;
	default:	goto yy41;
	}
yy41:
#line 286 "c_token.tem.c"
	{ ADD_TOKEN('-'); continue;}
#line 528 "c_token.c"
yy42:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy101;
	default:	goto yy43;
	}
yy43:
#line 288 "c_token.tem.c"
	{ ADD_TOKEN('*'); continue;}
#line 538 "c_token.c"
yy44:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy99;
	default:	goto yy45;
	}
yy45:
#line 290 "c_token.tem.c"
	{ ADD_TOKEN('%'); continue;}
#line 548 "c_token.c"
yy46:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '&':	goto yy95;
	case '=':	goto yy97;
	default:	goto yy47;
	}
yy47:
#line 283 "c_token.tem.c"
	{ ADD_TOKEN('&'); continue;}
#line 559 "c_token.c"
yy48:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy93;
	default:	goto yy49;
	}
yy49:
#line 293 "c_token.tem.c"
	{ ADD_TOKEN('^'); continue;}
#line 569 "c_token.c"
yy50:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy91;
	case '|':	goto yy89;
	default:	goto yy51;
	}
yy51:
#line 294 "c_token.tem.c"
	{ ADD_TOKEN('|'); continue;}
#line 580 "c_token.c"
yy52:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy87;
	default:	goto yy53;
	}
yy53:
#line 277 "c_token.tem.c"
	{ ADD_TOKEN('='); continue;}
#line 590 "c_token.c"
yy54:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy85;
	default:	goto yy55;
	}
yy55:
#line 284 "c_token.tem.c"
	{ ADD_TOKEN('!'); continue;}
#line 600 "c_token.c"
yy56:
	++YYCURSOR;
#line 272 "c_token.tem.c"
	{ ADD_TOKEN(';'); continue;}
#line 605 "c_token.c"
yy58:
	++YYCURSOR;
#line 273 "c_token.tem.c"
	{ ADD_TOKEN('{'); continue;}
#line 610 "c_token.c"
yy60:
	++YYCURSOR;
#line 274 "c_token.tem.c"
	{ ADD_TOKEN('}'); continue;}
#line 615 "c_token.c"
yy62:
	++YYCURSOR;
#line 275 "c_token.tem.c"
	{ ADD_TOKEN(','); continue;}
#line 620 "c_token.c"
yy64:
	++YYCURSOR;
#line 276 "c_token.tem.c"
	{ ADD_TOKEN(':'); continue;}
#line 625 "c_token.c"
yy66:
	++YYCURSOR;
#line 278 "c_token.tem.c"
	{ ADD_TOKEN('('); continue;}
#line 630 "c_token.c"
yy68:
	++YYCURSOR;
#line 279 "c_token.tem.c"
	{ ADD_TOKEN(')'); continue;}
#line 635 "c_token.c"
yy70:
	++YYCURSOR;
#line 280 "c_token.tem.c"
	{ ADD_TOKEN('['); continue;}
#line 640 "c_token.c"
yy72:
	++YYCURSOR;
#line 281 "c_token.tem.c"
	{ ADD_TOKEN(']'); continue;}
#line 645 "c_token.c"
yy74:
	++YYCURSOR;
#line 285 "c_token.tem.c"
	{ ADD_TOKEN('~'); continue;}
#line 650 "c_token.c"
yy76:
	++YYCURSOR;
#line 295 "c_token.tem.c"
	{ ADD_TOKEN('?'); continue;}
#line 655 "c_token.c"
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy84;
	default:	goto yy30;
	}
yy79:
	++YYCURSOR;
yy80:
#line 299 "c_token.tem.c"
	{
			ADD_TOKEN(NEWLINE);
			lineStart = yyCursor;
			currLine++;
			continue;
		}
#line 672 "c_token.c"
yy81:
	++YYCURSOR;
#line 305 "c_token.tem.c"
	{ADD_TOKEN(EOFILE); free(buffer); return 0; }
#line 677 "c_token.c"
yy83:
	yych = *++YYCURSOR;
	goto yy30;
yy84:
	yych = *++YYCURSOR;
	goto yy80;
yy85:
	++YYCURSOR;
#line 271 "c_token.tem.c"
	{ ADD_TOKEN(NEQ); continue;}
#line 688 "c_token.c"
yy87:
	++YYCURSOR;
#line 270 "c_token.tem.c"
	{ ADD_TOKEN(EQL); continue;}
#line 693 "c_token.c"
yy89:
	++YYCURSOR;
#line 267 "c_token.tem.c"
	{ ADD_TOKEN(OROR); continue;}
#line 698 "c_token.c"
yy91:
	++YYCURSOR;
#line 260 "c_token.tem.c"
	{ ADD_TOKEN(OREQ); continue;}
#line 703 "c_token.c"
yy93:
	++YYCURSOR;
#line 259 "c_token.tem.c"
	{ ADD_TOKEN(XOREQ); continue;}
#line 708 "c_token.c"
yy95:
	++YYCURSOR;
#line 266 "c_token.tem.c"
	{ ADD_TOKEN(ANDAND); continue;}
#line 713 "c_token.c"
yy97:
	++YYCURSOR;
#line 258 "c_token.tem.c"
	{ ADD_TOKEN(ANDEQ); continue;}
#line 718 "c_token.c"
yy99:
	++YYCURSOR;
#line 257 "c_token.tem.c"
	{ ADD_TOKEN(MODEQ); continue;}
#line 723 "c_token.c"
yy101:
	++YYCURSOR;
#line 255 "c_token.tem.c"
	{ ADD_TOKEN(MULEQ); continue;}
#line 728 "c_token.c"
yy103:
	++YYCURSOR;
#line 265 "c_token.tem.c"
	{ ADD_TOKEN(DEREF); continue;}
#line 733 "c_token.c"
yy105:
	++YYCURSOR;
#line 264 "c_token.tem.c"
	{ ADD_TOKEN(DECR); continue;}
#line 738 "c_token.c"
yy107:
	++YYCURSOR;
#line 254 "c_token.tem.c"
	{ ADD_TOKEN(SUBEQ); continue;}
#line 743 "c_token.c"
yy109:
	++YYCURSOR;
#line 263 "c_token.tem.c"
	{ ADD_TOKEN(INCR); continue;}
#line 748 "c_token.c"
yy111:
	++YYCURSOR;
#line 253 "c_token.tem.c"
	{ ADD_TOKEN(ADDEQ); continue;}
#line 753 "c_token.c"
yy113:
	++YYCURSOR;
#line 268 "c_token.tem.c"
	{ ADD_TOKEN(LEQ); continue;}
#line 758 "c_token.c"
yy115:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy117;
	default:	goto yy116;
	}
yy116:
#line 262 "c_token.tem.c"
	{ ADD_TOKEN(LSHIFT); continue;}
#line 768 "c_token.c"
yy117:
	++YYCURSOR;
#line 252 "c_token.tem.c"
	{ ADD_TOKEN(LSHIFTEQ); continue;}
#line 773 "c_token.c"
yy119:
	++YYCURSOR;
#line 269 "c_token.tem.c"
	{ ADD_TOKEN(GEQ); continue;}
#line 778 "c_token.c"
yy121:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy123;
	default:	goto yy122;
	}
yy122:
#line 261 "c_token.tem.c"
	{ ADD_TOKEN(RSHIFT); continue;}
#line 788 "c_token.c"
yy123:
	++YYCURSOR;
#line 251 "c_token.tem.c"
	{ ADD_TOKEN(RSHIFTEQ); continue;}
#line 793 "c_token.c"
yy125:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy126:
	switch (yych) {
	case '\n':	goto yy127;
	case '"':	goto yy129;
	case '\\':	goto yy128;
	default:	goto yy125;
	}
yy127:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy22;
	case 1: 	goto yy24;
	case 2: 	goto yy27;
	case 3: 	goto yy30;
	case 4: 	goto yy32;
	case 5: 	goto yy139;
	case 6: 	goto yy201;
	}
yy128:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy125;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy132;
	case 'x':	goto yy131;
	default:	goto yy127;
	}
yy129:
	++YYCURSOR;
#line 248 "c_token.tem.c"
	{ ADD_TOKEN(SCON); continue;}
#line 847 "c_token.c"
yy131:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy134;
	default:	goto yy127;
	}
yy132:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy127;
	case '"':	goto yy129;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy132;
	case '\\':	goto yy128;
	default:	goto yy125;
	}
yy134:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy127;
	case '"':	goto yy129;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy134;
	case '\\':	goto yy128;
	default:	goto yy125;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy145;
	default:	goto yy127;
	}
yy137:
	yyaccept = 5;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy137;
	case 'E':
	case 'e':	goto yy140;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy141;
	default:	goto yy139;
	}
yy139:
#line 245 "c_token.tem.c"
	{ ADD_TOKEN(FCON); continue;}
#line 960 "c_token.c"
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy142;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy143;
	default:	goto yy127;
	}
yy141:
	yych = *++YYCURSOR;
	goto yy139;
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy143;
	default:	goto yy127;
	}
yy143:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy143;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy141;
	default:	goto yy139;
	}
yy145:
	++YYCURSOR;
#line 250 "c_token.tem.c"
	{ ADD_TOKEN(ELLIPSIS); continue;}
#line 1021 "c_token.c"
yy147:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy148:
	switch (yych) {
	case '\n':	goto yy127;
	case '\'':	goto yy150;
	case '\\':	goto yy149;
	default:	goto yy147;
	}
yy149:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy147;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy152;
	case 'x':	goto yy151;
	default:	goto yy127;
	}
yy150:
	yych = *++YYCURSOR;
	goto yy27;
yy151:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy154;
	default:	goto yy127;
	}
yy152:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy127;
	case '\'':	goto yy150;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy152;
	case '\\':	goto yy149;
	default:	goto yy147;
	}
yy154:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy127;
	case '\'':	goto yy150;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy154;
	case '\\':	goto yy149;
	default:	goto yy147;
	}
yy156:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy167;
	default:	goto yy166;
	}
yy157:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy158:
	switch (yych) {
	case '.':	goto yy156;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy157;
	case 'E':
	case 'e':	goto yy159;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy160;
	default:	goto yy27;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy162;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy163;
	default:	goto yy127;
	}
yy160:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy160;
	default:	goto yy27;
	}
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy163;
	default:	goto yy127;
	}
yy163:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy163;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy141;
	default:	goto yy139;
	}
yy165:
	yyaccept = 5;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
yy166:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy165;
	case 'E':
	case 'e':	goto yy171;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy141;
	default:	goto yy139;
	}
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy168;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy169;
	default:	goto yy127;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy169;
	default:	goto yy127;
	}
yy169:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy169;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy141;
	default:	goto yy139;
	}
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy172;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy173;
	default:	goto yy127;
	}
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy173;
	default:	goto yy127;
	}
yy173:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy173;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy141;
	default:	goto yy139;
	}
yy175:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy176:
	switch (yych) {
	case '.':	goto yy156;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy175;
	case 'E':
	case 'e':	goto yy159;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy182;
	default:	goto yy27;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy178;
	default:	goto yy127;
	}
yy178:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy178;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy180;
	default:	goto yy27;
	}
yy180:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy180;
	default:	goto yy27;
	}
yy182:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy182;
	default:	goto yy27;
	}
yy184:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy185:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy5;
	}
yy186:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
yy187:
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy186;
	case '#':	goto yy188;
	default:	goto yy24;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case '#':	goto yy189;
	default:	goto yy127;
	}
yy189:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy189;
	default:	goto yy191;
	}
yy191:
#line 228 "c_token.tem.c"
	{ ADD_TOKEN(PP_DSHARP); continue;}
#line 1584 "c_token.c"
yy192:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
yy193:
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy192;
	case 'd':	goto yy198;
	case 'e':	goto yy195;
	case 'i':	goto yy199;
	case 'l':	goto yy196;
	case 'p':	goto yy194;
	case 'u':	goto yy197;
	default:	goto yy22;
	}
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy242;
	default:	goto yy127;
	}
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy228;
	case 'n':	goto yy229;
	case 'r':	goto yy230;
	default:	goto yy127;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy224;
	default:	goto yy127;
	}
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy219;
	default:	goto yy127;
	}
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy213;
	default:	goto yy127;
	}
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy200;
	case 'n':	goto yy202;
	default:	goto yy127;
	}
yy200:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'd':	goto yy209;
	default:	goto yy201;
	}
yy201:
#line 217 "c_token.tem.c"
	{ ADD_TOKEN(PP_IF); continue;}
#line 1653 "c_token.c"
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy203;
	default:	goto yy127;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy204;
	default:	goto yy127;
	}
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy205;
	default:	goto yy127;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy206;
	default:	goto yy127;
	}
yy206:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy207;
	default:	goto yy127;
	}
yy207:
	++YYCURSOR;
#line 221 "c_token.tem.c"
	{ ADD_TOKEN(PP_INCLUDE); continue;}
#line 1688 "c_token.c"
yy209:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy210;
	default:	goto yy127;
	}
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy211;
	default:	goto yy127;
	}
yy211:
	++YYCURSOR;
#line 219 "c_token.tem.c"
	{ ADD_TOKEN(PP_IFDEF); continue;}
#line 1705 "c_token.c"
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy214;
	default:	goto yy127;
	}
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy215;
	default:	goto yy127;
	}
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy216;
	default:	goto yy127;
	}
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy217;
	default:	goto yy127;
	}
yy217:
	++YYCURSOR;
#line 222 "c_token.tem.c"
	{ ADD_TOKEN(PP_DEFINE); continue;}
#line 1734 "c_token.c"
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy220;
	default:	goto yy127;
	}
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy221;
	default:	goto yy127;
	}
yy221:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy222;
	default:	goto yy127;
	}
yy222:
	++YYCURSOR;
#line 223 "c_token.tem.c"
	{ ADD_TOKEN(PP_UNDEF); continue;}
#line 1757 "c_token.c"
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy225;
	default:	goto yy127;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy226;
	default:	goto yy127;
	}
yy226:
	++YYCURSOR;
#line 224 "c_token.tem.c"
	{ ADD_TOKEN(PP_LINE); continue;}
#line 1774 "c_token.c"
yy228:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy239;
	default:	goto yy127;
	}
yy229:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy235;
	default:	goto yy127;
	}
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy231;
	default:	goto yy127;
	}
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy232;
	default:	goto yy127;
	}
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy233;
	default:	goto yy127;
	}
yy233:
	++YYCURSOR;
#line 225 "c_token.tem.c"
	{ ADD_TOKEN(PP_ERROR); continue;}
#line 1809 "c_token.c"
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy236;
	default:	goto yy127;
	}
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy237;
	default:	goto yy127;
	}
yy237:
	++YYCURSOR;
#line 220 "c_token.tem.c"
	{ ADD_TOKEN(PP_ENDIF); continue;}
#line 1826 "c_token.c"
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy240;
	default:	goto yy127;
	}
yy240:
	++YYCURSOR;
#line 218 "c_token.tem.c"
	{ ADD_TOKEN(PP_ELSE); continue;}
#line 1837 "c_token.c"
yy242:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy243;
	default:	goto yy127;
	}
yy243:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy244;
	default:	goto yy127;
	}
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy245;
	default:	goto yy127;
	}
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy246;
	default:	goto yy127;
	}
yy246:
	++YYCURSOR;
#line 226 "c_token.tem.c"
	{ ADD_TOKEN(PP_PRAGMA); continue;}
#line 1866 "c_token.c"
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':	goto yy254;
	case 'F':	goto yy253;
	case 'L':	goto yy252;
	case 'S':	goto yy255;
	case 'a':	goto yy249;
	case 'i':	goto yy251;
	case 'r':	goto yy250;
	default:	goto yy185;
	}
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy298;
	default:	goto yy185;
	}
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy288;
	default:	goto yy185;
	}
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy280;
	default:	goto yy185;
	}
yy252:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':	goto yy274;
	default:	goto yy185;
	}
yy253:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':	goto yy268;
	default:	goto yy185;
	}
yy254:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':	goto yy262;
	default:	goto yy185;
	}
yy255:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy256;
	default:	goto yy185;
	}
yy256:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':	goto yy257;
	default:	goto yy185;
	}
yy257:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':	goto yy258;
	default:	goto yy185;
	}
yy258:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy259;
	default:	goto yy185;
	}
yy259:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy260;
	default:	goto yy185;
	}
yy260:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy261;
	}
yy261:
#line 233 "c_token.tem.c"
	{ ADD_TOKEN(PP_STDC); continue;}
#line 2016 "c_token.c"
yy262:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy263;
	default:	goto yy185;
	}
yy263:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':	goto yy264;
	default:	goto yy185;
	}
yy264:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy265;
	default:	goto yy185;
	}
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy266;
	default:	goto yy185;
	}
yy266:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy267;
	}
yy267:
#line 232 "c_token.tem.c"
	{ ADD_TOKEN(PP_DATE); continue;}
#line 2112 "c_token.c"
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy269;
	default:	goto yy185;
	}
yy269:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':	goto yy270;
	default:	goto yy185;
	}
yy270:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy271;
	default:	goto yy185;
	}
yy271:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy272;
	default:	goto yy185;
	}
yy272:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy273;
	}
yy273:
#line 231 "c_token.tem.c"
	{ ADD_TOKEN(PP_FILE); continue;}
#line 2208 "c_token.c"
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':	goto yy275;
	default:	goto yy185;
	}
yy275:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':	goto yy276;
	default:	goto yy185;
	}
yy276:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy277;
	default:	goto yy185;
	}
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy278;
	default:	goto yy185;
	}
yy278:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy279;
	}
yy279:
#line 230 "c_token.tem.c"
	{ ADD_TOKEN(PP_LINENO); continue;}
#line 2304 "c_token.c"
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy281;
	default:	goto yy185;
	}
yy281:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy282;
	default:	goto yy185;
	}
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy283;
	default:	goto yy185;
	}
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy284;
	default:	goto yy185;
	}
yy284:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy285;
	default:	goto yy185;
	}
yy285:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy286;
	default:	goto yy185;
	}
yy286:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy287;
	}
yy287:
#line 214 "c_token.tem.c"
	{ ADD_TOKEN(INLINE); continue;}
#line 2412 "c_token.c"
yy288:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy289;
	default:	goto yy185;
	}
yy289:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy290;
	default:	goto yy185;
	}
yy290:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy291;
	default:	goto yy185;
	}
yy291:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy292;
	default:	goto yy185;
	}
yy292:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy293;
	default:	goto yy185;
	}
yy293:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy294;
	default:	goto yy185;
	}
yy294:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy295;
	default:	goto yy185;
	}
yy295:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy296;
	default:	goto yy185;
	}
yy296:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy297;
	}
yy297:
#line 213 "c_token.tem.c"
	{ADD_TOKEN(RESTRICT); continue;}
#line 2532 "c_token.c"
yy298:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy299;
	default:	goto yy185;
	}
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy300;
	default:	goto yy185;
	}
yy300:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy301;
	default:	goto yy185;
	}
yy301:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy302;
	default:	goto yy185;
	}
yy302:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy303;
	default:	goto yy185;
	}
yy303:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy304;
	default:	goto yy185;
	}
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy305;
	default:	goto yy185;
	}
yy305:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy306;
	default:	goto yy185;
	}
yy306:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy307;
	default:	goto yy185;
	}
yy307:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy308;
	}
yy308:
#line 211 "c_token.tem.c"
	{ ADD_TOKEN(ATTRIBUTE); continue;}
#line 2658 "c_token.c"
yy309:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy310;
	default:	goto yy185;
	}
yy310:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy311;
	default:	goto yy185;
	}
yy311:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy312;
	default:	goto yy185;
	}
yy312:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy313;
	}
yy313:
#line 210 "c_token.tem.c"
	{ ADD_TOKEN(WHILE); continue;}
#line 2748 "c_token.c"
yy314:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy315;
	case 'l':	goto yy316;
	default:	goto yy185;
	}
yy315:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy323;
	default:	goto yy185;
	}
yy316:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy317;
	default:	goto yy185;
	}
yy317:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy318;
	default:	goto yy185;
	}
yy318:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy319;
	default:	goto yy185;
	}
yy319:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy320;
	default:	goto yy185;
	}
yy320:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy321;
	default:	goto yy185;
	}
yy321:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy322;
	}
yy322:
#line 209 "c_token.tem.c"
	{ ADD_TOKEN(VOLATILE); continue;}
#line 2863 "c_token.c"
yy323:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy324;
	}
yy324:
#line 208 "c_token.tem.c"
	{ ADD_TOKEN(VOID); continue;}
#line 2935 "c_token.c"
yy325:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy326;
	case 's':	goto yy327;
	default:	goto yy185;
	}
yy326:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy334;
	default:	goto yy185;
	}
yy327:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy328;
	default:	goto yy185;
	}
yy328:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy329;
	default:	goto yy185;
	}
yy329:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy330;
	default:	goto yy185;
	}
yy330:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy331;
	default:	goto yy185;
	}
yy331:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy332;
	default:	goto yy185;
	}
yy332:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy333;
	}
yy333:
#line 207 "c_token.tem.c"
	{ ADD_TOKEN(UNSIGNED); continue;}
#line 3050 "c_token.c"
yy334:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy335;
	default:	goto yy185;
	}
yy335:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy336;
	}
yy336:
#line 206 "c_token.tem.c"
	{ ADD_TOKEN(UNION); continue;}
#line 3128 "c_token.c"
yy337:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy338;
	default:	goto yy185;
	}
yy338:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy339;
	default:	goto yy185;
	}
yy339:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy340;
	default:	goto yy185;
	}
yy340:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy341;
	default:	goto yy185;
	}
yy341:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy342;
	default:	goto yy185;
	}
yy342:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy343;
	}
yy343:
#line 205 "c_token.tem.c"
	{ ADD_TOKEN(TYPEDEF); continue;}
#line 3230 "c_token.c"
yy344:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy373;
	default:	goto yy185;
	}
yy345:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy363;
	case 'z':	goto yy364;
	default:	goto yy185;
	}
yy346:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy353;
	case 'r':	goto yy354;
	default:	goto yy185;
	}
yy347:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy348;
	default:	goto yy185;
	}
yy348:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy349;
	default:	goto yy185;
	}
yy349:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy350;
	default:	goto yy185;
	}
yy350:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy351;
	default:	goto yy185;
	}
yy351:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy352;
	}
yy352:
#line 204 "c_token.tem.c"
	{ ADD_TOKEN(SWITCH); continue;}
#line 3346 "c_token.c"
yy353:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy359;
	default:	goto yy185;
	}
yy354:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy355;
	default:	goto yy185;
	}
yy355:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy356;
	default:	goto yy185;
	}
yy356:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy357;
	default:	goto yy185;
	}
yy357:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy358;
	}
yy358:
#line 203 "c_token.tem.c"
	{ ADD_TOKEN(STRUCT); continue;}
#line 3442 "c_token.c"
yy359:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy360;
	default:	goto yy185;
	}
yy360:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy361;
	default:	goto yy185;
	}
yy361:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy362;
	}
yy362:
#line 202 "c_token.tem.c"
	{ ADD_TOKEN(STATIC); continue;}
#line 3526 "c_token.c"
yy363:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy369;
	default:	goto yy185;
	}
yy364:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy365;
	default:	goto yy185;
	}
yy365:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy366;
	default:	goto yy185;
	}
yy366:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy367;
	default:	goto yy185;
	}
yy367:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy368;
	}
yy368:
#line 201 "c_token.tem.c"
	{ ADD_TOKEN(SIZEOF); continue;}
#line 3622 "c_token.c"
yy369:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy370;
	default:	goto yy185;
	}
yy370:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy371;
	default:	goto yy185;
	}
yy371:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy372;
	}
yy372:
#line 200 "c_token.tem.c"
	{ ADD_TOKEN(SIGNED); continue;}
#line 3706 "c_token.c"
yy373:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy374;
	default:	goto yy185;
	}
yy374:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy375;
	default:	goto yy185;
	}
yy375:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy376;
	}
yy376:
#line 199 "c_token.tem.c"
	{ ADD_TOKEN(SHORT); continue;}
#line 3790 "c_token.c"
yy377:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy378;
	case 't':	goto yy379;
	default:	goto yy185;
	}
yy378:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy384;
	default:	goto yy185;
	}
yy379:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy380;
	default:	goto yy185;
	}
yy380:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy381;
	default:	goto yy185;
	}
yy381:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy382;
	default:	goto yy185;
	}
yy382:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy383;
	}
yy383:
#line 198 "c_token.tem.c"
	{ ADD_TOKEN(RETURN); continue;}
#line 3893 "c_token.c"
yy384:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy385;
	default:	goto yy185;
	}
yy385:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy386;
	default:	goto yy185;
	}
yy386:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy387;
	default:	goto yy185;
	}
yy387:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy388;
	default:	goto yy185;
	}
yy388:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy389;
	}
yy389:
#line 197 "c_token.tem.c"
	{ ADD_TOKEN(REGISTER); continue;}
#line 3989 "c_token.c"
yy390:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy391;
	default:	goto yy185;
	}
yy391:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy392;
	default:	goto yy185;
	}
yy392:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy393;
	}
yy393:
#line 196 "c_token.tem.c"
	{ ADD_TOKEN(LONG); continue;}
#line 4073 "c_token.c"
yy394:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy395;
	}
yy395:
#line 194 "c_token.tem.c"
	{ ADD_TOKEN(IF); continue;}
#line 4145 "c_token.c"
yy396:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy399;
	case 't':	goto yy397;
	default:	goto yy185;
	}
yy397:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy398;
	}
yy398:
#line 195 "c_token.tem.c"
	{ ADD_TOKEN(INT); continue;}
#line 4224 "c_token.c"
yy399:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy400;
	default:	goto yy185;
	}
yy400:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy401;
	default:	goto yy185;
	}
yy401:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy402;
	default:	goto yy185;
	}
yy402:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy403;
	}
yy403:
#line 212 "c_token.tem.c"
	{ ADD_TOKEN(INLINE); continue;}
#line 4314 "c_token.c"
yy404:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy405;
	default:	goto yy185;
	}
yy405:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy406;
	default:	goto yy185;
	}
yy406:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy407;
	}
yy407:
#line 193 "c_token.tem.c"
	{ ADD_TOKEN(GOTO); continue;}
#line 4398 "c_token.c"
yy408:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy412;
	default:	goto yy185;
	}
yy409:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy410;
	default:	goto yy185;
	}
yy410:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy411;
	}
yy411:
#line 192 "c_token.tem.c"
	{ ADD_TOKEN(FOR); continue;}
#line 4482 "c_token.c"
yy412:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy413;
	default:	goto yy185;
	}
yy413:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy414;
	default:	goto yy185;
	}
yy414:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy415;
	}
yy415:
#line 191 "c_token.tem.c"
	{ ADD_TOKEN(FLOAT); continue;}
#line 4566 "c_token.c"
yy416:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy431;
	default:	goto yy185;
	}
yy417:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy428;
	default:	goto yy185;
	}
yy418:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy425;
	default:	goto yy185;
	}
yy419:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy420;
	default:	goto yy185;
	}
yy420:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy421;
	default:	goto yy185;
	}
yy421:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy422;
	default:	goto yy185;
	}
yy422:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy423;
	default:	goto yy185;
	}
yy423:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy424;
	}
yy424:
#line 190 "c_token.tem.c"
	{ ADD_TOKEN(EXTERN); continue;}
#line 4680 "c_token.c"
yy425:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy426;
	default:	goto yy185;
	}
yy426:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy427;
	}
yy427:
#line 234 "c_token.tem.c"
	{ ADD_TOKEN(PP_EVAL); continue;}
#line 4758 "c_token.c"
yy428:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy429;
	default:	goto yy185;
	}
yy429:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy430;
	}
yy430:
#line 189 "c_token.tem.c"
	{ ADD_TOKEN(ENUM); continue;}
#line 4836 "c_token.c"
yy431:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy432;
	default:	goto yy185;
	}
yy432:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy433;
	}
yy433:
#line 188 "c_token.tem.c"
	{ ADD_TOKEN(ELSE); continue;}
#line 4914 "c_token.c"
yy434:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy442;
	default:	goto yy185;
	}
yy435:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	case 'u':	goto yy437;
	default:	goto yy436;
	}
yy436:
#line 186 "c_token.tem.c"
	{ ADD_TOKEN(DO); continue;}
#line 4992 "c_token.c"
yy437:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy438;
	default:	goto yy185;
	}
yy438:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy439;
	default:	goto yy185;
	}
yy439:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy440;
	default:	goto yy185;
	}
yy440:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy441;
	}
yy441:
#line 187 "c_token.tem.c"
	{ ADD_TOKEN(DOUBLE); continue;}
#line 5082 "c_token.c"
yy442:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy443;
	case 'i':	goto yy444;
	default:	goto yy185;
	}
yy443:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy448;
	default:	goto yy185;
	}
yy444:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy445;
	default:	goto yy185;
	}
yy445:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy446;
	default:	goto yy185;
	}
yy446:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy447;
	}
yy447:
#line 229 "c_token.tem.c"
	{ ADD_TOKEN(PP_DEFINED); continue;}
#line 5179 "c_token.c"
yy448:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy449;
	default:	goto yy185;
	}
yy449:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy450;
	default:	goto yy185;
	}
yy450:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy451;
	}
yy451:
#line 185 "c_token.tem.c"
	{ ADD_TOKEN(DEFAULT); continue;}
#line 5263 "c_token.c"
yy452:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy468;
	default:	goto yy185;
	}
yy453:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy465;
	default:	goto yy185;
	}
yy454:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy455;
	default:	goto yy185;
	}
yy455:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy456;
	case 't':	goto yy457;
	default:	goto yy185;
	}
yy456:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy463;
	default:	goto yy185;
	}
yy457:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy458;
	default:	goto yy185;
	}
yy458:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy459;
	default:	goto yy185;
	}
yy459:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy460;
	default:	goto yy185;
	}
yy460:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy461;
	default:	goto yy185;
	}
yy461:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy462;
	}
yy462:
#line 184 "c_token.tem.c"
	{ ADD_TOKEN(CONTINUE); continue;}
#line 5390 "c_token.c"
yy463:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy464;
	}
yy464:
#line 183 "c_token.tem.c"
	{ ADD_TOKEN(CONST); continue;}
#line 5462 "c_token.c"
yy465:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy466;
	default:	goto yy185;
	}
yy466:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy467;
	}
yy467:
#line 182 "c_token.tem.c"
	{ ADD_TOKEN(CHAR); continue;}
#line 5540 "c_token.c"
yy468:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy469;
	default:	goto yy185;
	}
yy469:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy470;
	}
yy470:
#line 181 "c_token.tem.c"
	{ ADD_TOKEN(CASE); continue;}
#line 5618 "c_token.c"
yy471:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy472;
	default:	goto yy185;
	}
yy472:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy473;
	default:	goto yy185;
	}
yy473:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'k':	goto yy474;
	default:	goto yy185;
	}
yy474:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy475;
	}
yy475:
#line 180 "c_token.tem.c"
	{ ADD_TOKEN(BREAK); continue;}
#line 5708 "c_token.c"
yy476:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy477;
	default:	goto yy185;
	}
yy477:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy478;
	default:	goto yy185;
	}
yy478:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy184;
	default:	goto yy479;
	}
yy479:
#line 179 "c_token.tem.c"
	{ ADD_TOKEN(AUTO); continue;}
#line 5792 "c_token.c"
yy480:
	++YYCURSOR;
#line 256 "c_token.tem.c"
	{ ADD_TOKEN(DIVEQ); continue;}
#line 5797 "c_token.c"
yy482:
	++YYCURSOR;
#line 177 "c_token.tem.c"
	{ goto cppcomment;}
#line 5802 "c_token.c"
yy484:
	++YYCURSOR;
#line 176 "c_token.tem.c"
	{ goto comment; }
#line 5807 "c_token.c"
}
#line 311 "c_token.tem.c"

		comment:
		
#line 5813 "c_token.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy491;
	case '\r':	goto yy490;
	case '*':	goto yy488;
	default:	goto yy493;
	}
yy488:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '/':	goto yy495;
	default:	goto yy489;
	}
yy489:
#line 321 "c_token.tem.c"
	{ goto comment; }
#line 5833 "c_token.c"
yy490:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy494;
	default:	goto yy489;
	}
yy491:
	++YYCURSOR;
yy492:
#line 316 "c_token.tem.c"
	{
			lineStart = yyCursor;
			currLine++;
			goto comment;
		}
#line 5849 "c_token.c"
yy493:
	yych = *++YYCURSOR;
	goto yy489;
yy494:
	yych = *++YYCURSOR;
	goto yy492;
yy495:
	++YYCURSOR;
#line 314 "c_token.tem.c"
	{ ADD_TOKEN(COMMENT); continue; }
#line 5860 "c_token.c"
}
#line 322 "c_token.tem.c"

		cppcomment:
		
#line 5866 "c_token.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy501;
	case '\r':	goto yy499;
	default:	goto yy503;
	}
yy499:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\n':	goto yy504;
	default:	goto yy500;
	}
yy500:
#line 332 "c_token.tem.c"
	{ goto cppcomment; }
#line 5885 "c_token.c"
yy501:
	++YYCURSOR;
yy502:
#line 326 "c_token.tem.c"
	{
			ADD_TOKEN(COMMENT);
			lineStart = yyCursor;
			currLine++;
			continue;
		}
#line 5896 "c_token.c"
yy503:
	yych = *++YYCURSOR;
	goto yy500;
yy504:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy502;
}
#line 333 "c_token.tem.c"

	}
}

